"""Initial tables

Revision ID: 5700592ef64b
Revises: 
Create Date: 2025-11-29 22:35:26.870862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5700592ef64b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id_no', sa.String(length=50), nullable=False),
    sa.Column('phone_no', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_no')
    )
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labor_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('labor_type', sa.String(length=20), nullable=False),
    sa.Column('wage_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('tasks_done', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labor_id'], ['labors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendances')
    op.drop_table('labors')
    # ### end Alembic commands ###
